---
name: Helm Publish

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/helm.yaml
      - "helm-chart/**"


env:
  REGISTRY_IMAGE: ghcr.io/radiant-maxar/cvat/charts

jobs:
  build:
    name: Push Chart
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Build Chart
        run: |
          helm dep up helm-chart
          helm package helm-chart

      - name: Helm Login to GitHub Registry
        run: |
          echo ${{ github.token }} | helm registry login ghcr.io --username ${{ github.repository_owner }} --password-stdin

      - name: Helm Push Chart to GitHub Registry
        run: |
          helm push cvat-*.tgz oci://${REGISTRY_IMAGE}
          rm -v cvat-*.tgz
